# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/otavio/atual/poo/agendaNew

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/otavio/atual/poo/agendaNew

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/otavio/atual/poo/agendaNew/CMakeFiles /home/otavio/atual/poo/agendaNew/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/otavio/atual/poo/agendaNew/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named agenda

# Build rule for target.
agenda: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 agenda
.PHONY : agenda

# fast build rule for target.
agenda/fast:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/build
.PHONY : agenda/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/main.cpp.s
.PHONY : main.cpp.s

src/Agenda.o: src/Agenda.cpp.o

.PHONY : src/Agenda.o

# target to build an object file
src/Agenda.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Agenda.cpp.o
.PHONY : src/Agenda.cpp.o

src/Agenda.i: src/Agenda.cpp.i

.PHONY : src/Agenda.i

# target to preprocess a source file
src/Agenda.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Agenda.cpp.i
.PHONY : src/Agenda.cpp.i

src/Agenda.s: src/Agenda.cpp.s

.PHONY : src/Agenda.s

# target to generate assembly for a file
src/Agenda.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Agenda.cpp.s
.PHONY : src/Agenda.cpp.s

src/Cidade.o: src/Cidade.cpp.o

.PHONY : src/Cidade.o

# target to build an object file
src/Cidade.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Cidade.cpp.o
.PHONY : src/Cidade.cpp.o

src/Cidade.i: src/Cidade.cpp.i

.PHONY : src/Cidade.i

# target to preprocess a source file
src/Cidade.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Cidade.cpp.i
.PHONY : src/Cidade.cpp.i

src/Cidade.s: src/Cidade.cpp.s

.PHONY : src/Cidade.s

# target to generate assembly for a file
src/Cidade.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Cidade.cpp.s
.PHONY : src/Cidade.cpp.s

src/Contato.o: src/Contato.cpp.o

.PHONY : src/Contato.o

# target to build an object file
src/Contato.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Contato.cpp.o
.PHONY : src/Contato.cpp.o

src/Contato.i: src/Contato.cpp.i

.PHONY : src/Contato.i

# target to preprocess a source file
src/Contato.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Contato.cpp.i
.PHONY : src/Contato.cpp.i

src/Contato.s: src/Contato.cpp.s

.PHONY : src/Contato.s

# target to generate assembly for a file
src/Contato.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Contato.cpp.s
.PHONY : src/Contato.cpp.s

src/Date.o: src/Date.cpp.o

.PHONY : src/Date.o

# target to build an object file
src/Date.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Date.cpp.o
.PHONY : src/Date.cpp.o

src/Date.i: src/Date.cpp.i

.PHONY : src/Date.i

# target to preprocess a source file
src/Date.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Date.cpp.i
.PHONY : src/Date.cpp.i

src/Date.s: src/Date.cpp.s

.PHONY : src/Date.s

# target to generate assembly for a file
src/Date.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Date.cpp.s
.PHONY : src/Date.cpp.s

src/DateException.o: src/DateException.cpp.o

.PHONY : src/DateException.o

# target to build an object file
src/DateException.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/DateException.cpp.o
.PHONY : src/DateException.cpp.o

src/DateException.i: src/DateException.cpp.i

.PHONY : src/DateException.i

# target to preprocess a source file
src/DateException.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/DateException.cpp.i
.PHONY : src/DateException.cpp.i

src/DateException.s: src/DateException.cpp.s

.PHONY : src/DateException.s

# target to generate assembly for a file
src/DateException.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/DateException.cpp.s
.PHONY : src/DateException.cpp.s

src/Endereco.o: src/Endereco.cpp.o

.PHONY : src/Endereco.o

# target to build an object file
src/Endereco.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Endereco.cpp.o
.PHONY : src/Endereco.cpp.o

src/Endereco.i: src/Endereco.cpp.i

.PHONY : src/Endereco.i

# target to preprocess a source file
src/Endereco.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Endereco.cpp.i
.PHONY : src/Endereco.cpp.i

src/Endereco.s: src/Endereco.cpp.s

.PHONY : src/Endereco.s

# target to generate assembly for a file
src/Endereco.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Endereco.cpp.s
.PHONY : src/Endereco.cpp.s

src/Estado.o: src/Estado.cpp.o

.PHONY : src/Estado.o

# target to build an object file
src/Estado.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Estado.cpp.o
.PHONY : src/Estado.cpp.o

src/Estado.i: src/Estado.cpp.i

.PHONY : src/Estado.i

# target to preprocess a source file
src/Estado.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Estado.cpp.i
.PHONY : src/Estado.cpp.i

src/Estado.s: src/Estado.cpp.s

.PHONY : src/Estado.s

# target to generate assembly for a file
src/Estado.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/Estado.cpp.s
.PHONY : src/Estado.cpp.s

src/ExpProfissional.o: src/ExpProfissional.cpp.o

.PHONY : src/ExpProfissional.o

# target to build an object file
src/ExpProfissional.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/ExpProfissional.cpp.o
.PHONY : src/ExpProfissional.cpp.o

src/ExpProfissional.i: src/ExpProfissional.cpp.i

.PHONY : src/ExpProfissional.i

# target to preprocess a source file
src/ExpProfissional.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/ExpProfissional.cpp.i
.PHONY : src/ExpProfissional.cpp.i

src/ExpProfissional.s: src/ExpProfissional.cpp.s

.PHONY : src/ExpProfissional.s

# target to generate assembly for a file
src/ExpProfissional.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/ExpProfissional.cpp.s
.PHONY : src/ExpProfissional.cpp.s

src/FormacaoAcad.o: src/FormacaoAcad.cpp.o

.PHONY : src/FormacaoAcad.o

# target to build an object file
src/FormacaoAcad.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/FormacaoAcad.cpp.o
.PHONY : src/FormacaoAcad.cpp.o

src/FormacaoAcad.i: src/FormacaoAcad.cpp.i

.PHONY : src/FormacaoAcad.i

# target to preprocess a source file
src/FormacaoAcad.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/FormacaoAcad.cpp.i
.PHONY : src/FormacaoAcad.cpp.i

src/FormacaoAcad.s: src/FormacaoAcad.cpp.s

.PHONY : src/FormacaoAcad.s

# target to generate assembly for a file
src/FormacaoAcad.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/FormacaoAcad.cpp.s
.PHONY : src/FormacaoAcad.cpp.s

src/InfoPessoal.o: src/InfoPessoal.cpp.o

.PHONY : src/InfoPessoal.o

# target to build an object file
src/InfoPessoal.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/InfoPessoal.cpp.o
.PHONY : src/InfoPessoal.cpp.o

src/InfoPessoal.i: src/InfoPessoal.cpp.i

.PHONY : src/InfoPessoal.i

# target to preprocess a source file
src/InfoPessoal.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/InfoPessoal.cpp.i
.PHONY : src/InfoPessoal.cpp.i

src/InfoPessoal.s: src/InfoPessoal.cpp.s

.PHONY : src/InfoPessoal.s

# target to generate assembly for a file
src/InfoPessoal.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/InfoPessoal.cpp.s
.PHONY : src/InfoPessoal.cpp.s

src/MenuPrincipal.o: src/MenuPrincipal.cpp.o

.PHONY : src/MenuPrincipal.o

# target to build an object file
src/MenuPrincipal.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/MenuPrincipal.cpp.o
.PHONY : src/MenuPrincipal.cpp.o

src/MenuPrincipal.i: src/MenuPrincipal.cpp.i

.PHONY : src/MenuPrincipal.i

# target to preprocess a source file
src/MenuPrincipal.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/MenuPrincipal.cpp.i
.PHONY : src/MenuPrincipal.cpp.i

src/MenuPrincipal.s: src/MenuPrincipal.cpp.s

.PHONY : src/MenuPrincipal.s

# target to generate assembly for a file
src/MenuPrincipal.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/MenuPrincipal.cpp.s
.PHONY : src/MenuPrincipal.cpp.s

src/StgAltContato.o: src/StgAltContato.cpp.o

.PHONY : src/StgAltContato.o

# target to build an object file
src/StgAltContato.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgAltContato.cpp.o
.PHONY : src/StgAltContato.cpp.o

src/StgAltContato.i: src/StgAltContato.cpp.i

.PHONY : src/StgAltContato.i

# target to preprocess a source file
src/StgAltContato.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgAltContato.cpp.i
.PHONY : src/StgAltContato.cpp.i

src/StgAltContato.s: src/StgAltContato.cpp.s

.PHONY : src/StgAltContato.s

# target to generate assembly for a file
src/StgAltContato.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgAltContato.cpp.s
.PHONY : src/StgAltContato.cpp.s

src/StgAlterar.o: src/StgAlterar.cpp.o

.PHONY : src/StgAlterar.o

# target to build an object file
src/StgAlterar.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgAlterar.cpp.o
.PHONY : src/StgAlterar.cpp.o

src/StgAlterar.i: src/StgAlterar.cpp.i

.PHONY : src/StgAlterar.i

# target to preprocess a source file
src/StgAlterar.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgAlterar.cpp.i
.PHONY : src/StgAlterar.cpp.i

src/StgAlterar.s: src/StgAlterar.cpp.s

.PHONY : src/StgAlterar.s

# target to generate assembly for a file
src/StgAlterar.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgAlterar.cpp.s
.PHONY : src/StgAlterar.cpp.s

src/StgExibir.o: src/StgExibir.cpp.o

.PHONY : src/StgExibir.o

# target to build an object file
src/StgExibir.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgExibir.cpp.o
.PHONY : src/StgExibir.cpp.o

src/StgExibir.i: src/StgExibir.cpp.i

.PHONY : src/StgExibir.i

# target to preprocess a source file
src/StgExibir.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgExibir.cpp.i
.PHONY : src/StgExibir.cpp.i

src/StgExibir.s: src/StgExibir.cpp.s

.PHONY : src/StgExibir.s

# target to generate assembly for a file
src/StgExibir.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgExibir.cpp.s
.PHONY : src/StgExibir.cpp.s

src/StgExportar.o: src/StgExportar.cpp.o

.PHONY : src/StgExportar.o

# target to build an object file
src/StgExportar.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgExportar.cpp.o
.PHONY : src/StgExportar.cpp.o

src/StgExportar.i: src/StgExportar.cpp.i

.PHONY : src/StgExportar.i

# target to preprocess a source file
src/StgExportar.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgExportar.cpp.i
.PHONY : src/StgExportar.cpp.i

src/StgExportar.s: src/StgExportar.cpp.s

.PHONY : src/StgExportar.s

# target to generate assembly for a file
src/StgExportar.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgExportar.cpp.s
.PHONY : src/StgExportar.cpp.s

src/StgFiltroIdadeCargo.o: src/StgFiltroIdadeCargo.cpp.o

.PHONY : src/StgFiltroIdadeCargo.o

# target to build an object file
src/StgFiltroIdadeCargo.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgFiltroIdadeCargo.cpp.o
.PHONY : src/StgFiltroIdadeCargo.cpp.o

src/StgFiltroIdadeCargo.i: src/StgFiltroIdadeCargo.cpp.i

.PHONY : src/StgFiltroIdadeCargo.i

# target to preprocess a source file
src/StgFiltroIdadeCargo.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgFiltroIdadeCargo.cpp.i
.PHONY : src/StgFiltroIdadeCargo.cpp.i

src/StgFiltroIdadeCargo.s: src/StgFiltroIdadeCargo.cpp.s

.PHONY : src/StgFiltroIdadeCargo.s

# target to generate assembly for a file
src/StgFiltroIdadeCargo.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgFiltroIdadeCargo.cpp.s
.PHONY : src/StgFiltroIdadeCargo.cpp.s

src/StgImportar.o: src/StgImportar.cpp.o

.PHONY : src/StgImportar.o

# target to build an object file
src/StgImportar.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgImportar.cpp.o
.PHONY : src/StgImportar.cpp.o

src/StgImportar.i: src/StgImportar.cpp.i

.PHONY : src/StgImportar.i

# target to preprocess a source file
src/StgImportar.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgImportar.cpp.i
.PHONY : src/StgImportar.cpp.i

src/StgImportar.s: src/StgImportar.cpp.s

.PHONY : src/StgImportar.s

# target to generate assembly for a file
src/StgImportar.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgImportar.cpp.s
.PHONY : src/StgImportar.cpp.s

src/StgIncluir.o: src/StgIncluir.cpp.o

.PHONY : src/StgIncluir.o

# target to build an object file
src/StgIncluir.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgIncluir.cpp.o
.PHONY : src/StgIncluir.cpp.o

src/StgIncluir.i: src/StgIncluir.cpp.i

.PHONY : src/StgIncluir.i

# target to preprocess a source file
src/StgIncluir.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgIncluir.cpp.i
.PHONY : src/StgIncluir.cpp.i

src/StgIncluir.s: src/StgIncluir.cpp.s

.PHONY : src/StgIncluir.s

# target to generate assembly for a file
src/StgIncluir.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgIncluir.cpp.s
.PHONY : src/StgIncluir.cpp.s

src/StgListar.o: src/StgListar.cpp.o

.PHONY : src/StgListar.o

# target to build an object file
src/StgListar.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgListar.cpp.o
.PHONY : src/StgListar.cpp.o

src/StgListar.i: src/StgListar.cpp.i

.PHONY : src/StgListar.i

# target to preprocess a source file
src/StgListar.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgListar.cpp.i
.PHONY : src/StgListar.cpp.i

src/StgListar.s: src/StgListar.cpp.s

.PHONY : src/StgListar.s

# target to generate assembly for a file
src/StgListar.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgListar.cpp.s
.PHONY : src/StgListar.cpp.s

src/StgPesquisar.o: src/StgPesquisar.cpp.o

.PHONY : src/StgPesquisar.o

# target to build an object file
src/StgPesquisar.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgPesquisar.cpp.o
.PHONY : src/StgPesquisar.cpp.o

src/StgPesquisar.i: src/StgPesquisar.cpp.i

.PHONY : src/StgPesquisar.i

# target to preprocess a source file
src/StgPesquisar.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgPesquisar.cpp.i
.PHONY : src/StgPesquisar.cpp.i

src/StgPesquisar.s: src/StgPesquisar.cpp.s

.PHONY : src/StgPesquisar.s

# target to generate assembly for a file
src/StgPesquisar.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgPesquisar.cpp.s
.PHONY : src/StgPesquisar.cpp.s

src/StgRemover.o: src/StgRemover.cpp.o

.PHONY : src/StgRemover.o

# target to build an object file
src/StgRemover.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgRemover.cpp.o
.PHONY : src/StgRemover.cpp.o

src/StgRemover.i: src/StgRemover.cpp.i

.PHONY : src/StgRemover.i

# target to preprocess a source file
src/StgRemover.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgRemover.cpp.i
.PHONY : src/StgRemover.cpp.i

src/StgRemover.s: src/StgRemover.cpp.s

.PHONY : src/StgRemover.s

# target to generate assembly for a file
src/StgRemover.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgRemover.cpp.s
.PHONY : src/StgRemover.cpp.s

src/StgRetornar.o: src/StgRetornar.cpp.o

.PHONY : src/StgRetornar.o

# target to build an object file
src/StgRetornar.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgRetornar.cpp.o
.PHONY : src/StgRetornar.cpp.o

src/StgRetornar.i: src/StgRetornar.cpp.i

.PHONY : src/StgRetornar.i

# target to preprocess a source file
src/StgRetornar.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgRetornar.cpp.i
.PHONY : src/StgRetornar.cpp.i

src/StgRetornar.s: src/StgRetornar.cpp.s

.PHONY : src/StgRetornar.s

# target to generate assembly for a file
src/StgRetornar.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgRetornar.cpp.s
.PHONY : src/StgRetornar.cpp.s

src/StgSair.o: src/StgSair.cpp.o

.PHONY : src/StgSair.o

# target to build an object file
src/StgSair.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgSair.cpp.o
.PHONY : src/StgSair.cpp.o

src/StgSair.i: src/StgSair.cpp.i

.PHONY : src/StgSair.i

# target to preprocess a source file
src/StgSair.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgSair.cpp.i
.PHONY : src/StgSair.cpp.i

src/StgSair.s: src/StgSair.cpp.s

.PHONY : src/StgSair.s

# target to generate assembly for a file
src/StgSair.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgSair.cpp.s
.PHONY : src/StgSair.cpp.s

src/StgVoid.o: src/StgVoid.cpp.o

.PHONY : src/StgVoid.o

# target to build an object file
src/StgVoid.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgVoid.cpp.o
.PHONY : src/StgVoid.cpp.o

src/StgVoid.i: src/StgVoid.cpp.i

.PHONY : src/StgVoid.i

# target to preprocess a source file
src/StgVoid.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgVoid.cpp.i
.PHONY : src/StgVoid.cpp.i

src/StgVoid.s: src/StgVoid.cpp.s

.PHONY : src/StgVoid.s

# target to generate assembly for a file
src/StgVoid.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/src/StgVoid.cpp.s
.PHONY : src/StgVoid.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... agenda"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Agenda.o"
	@echo "... src/Agenda.i"
	@echo "... src/Agenda.s"
	@echo "... src/Cidade.o"
	@echo "... src/Cidade.i"
	@echo "... src/Cidade.s"
	@echo "... src/Contato.o"
	@echo "... src/Contato.i"
	@echo "... src/Contato.s"
	@echo "... src/Date.o"
	@echo "... src/Date.i"
	@echo "... src/Date.s"
	@echo "... src/DateException.o"
	@echo "... src/DateException.i"
	@echo "... src/DateException.s"
	@echo "... src/Endereco.o"
	@echo "... src/Endereco.i"
	@echo "... src/Endereco.s"
	@echo "... src/Estado.o"
	@echo "... src/Estado.i"
	@echo "... src/Estado.s"
	@echo "... src/ExpProfissional.o"
	@echo "... src/ExpProfissional.i"
	@echo "... src/ExpProfissional.s"
	@echo "... src/FormacaoAcad.o"
	@echo "... src/FormacaoAcad.i"
	@echo "... src/FormacaoAcad.s"
	@echo "... src/InfoPessoal.o"
	@echo "... src/InfoPessoal.i"
	@echo "... src/InfoPessoal.s"
	@echo "... src/MenuPrincipal.o"
	@echo "... src/MenuPrincipal.i"
	@echo "... src/MenuPrincipal.s"
	@echo "... src/StgAltContato.o"
	@echo "... src/StgAltContato.i"
	@echo "... src/StgAltContato.s"
	@echo "... src/StgAlterar.o"
	@echo "... src/StgAlterar.i"
	@echo "... src/StgAlterar.s"
	@echo "... src/StgExibir.o"
	@echo "... src/StgExibir.i"
	@echo "... src/StgExibir.s"
	@echo "... src/StgExportar.o"
	@echo "... src/StgExportar.i"
	@echo "... src/StgExportar.s"
	@echo "... src/StgFiltroIdadeCargo.o"
	@echo "... src/StgFiltroIdadeCargo.i"
	@echo "... src/StgFiltroIdadeCargo.s"
	@echo "... src/StgImportar.o"
	@echo "... src/StgImportar.i"
	@echo "... src/StgImportar.s"
	@echo "... src/StgIncluir.o"
	@echo "... src/StgIncluir.i"
	@echo "... src/StgIncluir.s"
	@echo "... src/StgListar.o"
	@echo "... src/StgListar.i"
	@echo "... src/StgListar.s"
	@echo "... src/StgPesquisar.o"
	@echo "... src/StgPesquisar.i"
	@echo "... src/StgPesquisar.s"
	@echo "... src/StgRemover.o"
	@echo "... src/StgRemover.i"
	@echo "... src/StgRemover.s"
	@echo "... src/StgRetornar.o"
	@echo "... src/StgRetornar.i"
	@echo "... src/StgRetornar.s"
	@echo "... src/StgSair.o"
	@echo "... src/StgSair.i"
	@echo "... src/StgSair.s"
	@echo "... src/StgVoid.o"
	@echo "... src/StgVoid.i"
	@echo "... src/StgVoid.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

